In [1]:
import tensorflow as tf
from pathlib import Path
import random
import numpy as np

In [49]:
modelnet_train_txt = './data/modelnet40_normal_resampled/modelnet40_test.txt'
modelnet_label_txt = './data/modelnet40_normal_resampled/modelnet40_shape_names.txt'

In [50]:
shape_names = dict()

with open(modelnet_label_txt, 'r') as f:
  lines = f.readlines()
  

for idx, line in enumerate(lines):
  shape_names[line[:-1]] = idx
  
shape_names

{'airplane': 0,
 'bathtub': 1,
 'bed': 2,
 'bench': 3,
 'bookshelf': 4,
 'bottle': 5,
 'bowl': 6,
 'car': 7,
 'chair': 8,
 'cone': 9,
 'cup': 10,
 'curtain': 11,
 'desk': 12,
 'door': 13,
 'dresser': 14,
 'flower_pot': 15,
 'glass_box': 16,
 'guitar': 17,
 'keyboard': 18,
 'lamp': 19,
 'laptop': 20,
 'mantel': 21,
 'monitor': 22,
 'night_stand': 23,
 'person': 24,
 'piano': 25,
 'plant': 26,
 'radio': 27,
 'range_hood': 28,
 'sink': 29,
 'sofa': 30,
 'stairs': 31,
 'stool': 32,
 'table': 33,
 'tent': 34,
 'toilet': 35,
 'tv_stand': 36,
 'vase': 37,
 'wardrobe': 38,
 'xbox': 39}

In [51]:
train_target = list()

with open(modelnet_train_txt, 'r') as f:
  lines = f.readlines()
  
for line in lines:
  number = line.split('_')[-1]
  label = line[:-(len(number)+1)]
  target = './data/modelnet40_normal_resampled/' + label + '/' + line[:-1] + '.txt'
  
  train_target.append((target, str(shape_names[label])))
  
train_target

[('./data/modelnet40_normal_resampled/airplane/airplane_0627.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0628.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0629.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0630.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0631.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0632.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0633.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0634.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0635.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0636.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0637.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0638.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0639.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airp

In [52]:
# random.shuffle(train_target)
train_target

[('./data/modelnet40_normal_resampled/airplane/airplane_0627.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0628.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0629.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0630.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0631.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0632.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0633.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0634.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0635.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0636.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0637.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0638.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airplane_0639.txt', '0'),
 ('./data/modelnet40_normal_resampled/airplane/airp

In [53]:
dataset = tf.data.Dataset.from_tensor_slices(train_target)

In [54]:
for data in dataset.take(10):
  print(data)

tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0627.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0628.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0629.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0630.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0631.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0632.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0633.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0634.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0635.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data

In [55]:
def get_points_from_file(tarin_target):
  file_path = tarin_target[0].numpy()
  label = int(tarin_target[1])
  with open(file_path, 'r') as f:
    points_and_normals = f.readlines()

  num_points = len(points_and_normals)
  points = np.zeros((num_points, 3))
  for idx, pnn in enumerate(points_and_normals):
    points[idx] = np.array(pnn.split(',')[0:3])
    
#   points = tf.convert_to_tensor(points, dtype=tf.float32)
  return points.reshape(-1), label

In [56]:
for data in dataset.take(10):
  dd = get_points_from_file(data)[0]
  print(get_points_from_file(data)[0].shape)

(30000,)
(30000,)
(30000,)
(30000,)
(30000,)
(30000,)
(30000,)
(30000,)
(30000,)
(30000,)


In [57]:
def _bytes_feature(value):
  """Returns a bytes_list from a string / byte."""
  if isinstance(value, type(tf.constant(0))):
    value = value.numpy() # BytesList won't unpack a string from an EagerTensor.
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _float_feature_list(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=value))


def _int64_feature(value):
  """Returns an int64_list from a bool / enum / int / uint."""
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

In [58]:
def serialize_example(data):
  """
  Creates a tf.Example message ready to be written to a file.
  """
  # Create a dictionary mapping the feature name to the tf.Example-compatible
  # data type.
  points, label = get_points_from_file(data)  
  feature = {
      'points': _float_feature_list(points) if len(points) > 1 else _float_feature(points) ,
      'label': _int64_feature(label),
  }

  # Create a Features message using tf.train.Example.

  example_proto = tf.train.Example(features=tf.train.Features(feature=feature))
  return example_proto.SerializeToString()

In [59]:
for data in dataset.take(100):
  print(data)
#   points, label = get_points_from_file(data)
  serialized_example = serialize_example(data)

tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0627.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0628.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0629.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0630.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0631.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0632.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0633.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0634.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0635.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data

tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0705.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0706.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0707.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0708.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0709.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0710.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0711.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0712.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data/modelnet40_normal_resampled/airplane/airplane_0713.txt' b'0'], shape=(2,), dtype=string)
tf.Tensor([b'./data

In [60]:
serialized_example

b'\n\xe8\xa9\x07\n\x0e\n\x05label\x12\x05\x1a\x03\n\x01\x00\n\xd4\xa9\x07\n\x06points\x12\xc8\xa9\x07\x12\xc4\xa9\x07\n\xc0\xa9\x07\x90\xdc\x1a\xbb-`\xc2=`\x1f\x9d\xbd\xf0\x16\xa8\xbe\xcf,\t\xbd\xb3\x0cq?\x1c|\xa1>|\xf2\xb0<\xa5\xbdq\xbfI\x9dP?\x81&\xc2>\xaf%\xe4\xbd\xa8\xc6;\xbf\x82\xff-<gD\xe9\xbd\xf8\xc2\xa4>B\x95\x1a=x\x9c2?w-\x01?\xbd\xfbc\xbd\xfa~\xea\xbd\x8b\xe1\xea6_A\x1a\xbd)\\\x0f\xbfo\xf0\x85<\xa0\x15\x18\xbd\x1a\xc0\xbb>\xd74??\xf5\xdb\xd7=\x0f\x0b\xd5\xbe\x8d\x97>?\xaa`\xd4=\xeeZB>\x0f\x9c\xb3\xbe,\x82\x7f\xbd\x0e-2\xbe\xf7\xe4\x81\xbe\xc0\xcf\xb8\xbd-C\x1c>\xfd\x87t\xbdu\x93\x18\xbe\x7fj|\xbe+\x18E?\xd9Z\x9f=\xcff\xd5\xbd1\x99j>|~\x18\xbd\xcb\x10G\xbeh"\x0c?B>h>\xd3\xde\xe0\xbd\x87\xa7W>&\xe4\x03\xbd\xfd\xf65\xbfb->=\x9e^)\xbd\x8f\xe4\xf2=\\ \x01\xbf\xe3\xdf\xa7=\xbd\x8cb\xbd\x07\xceY>a\xe0\xb9\xbc\x7f\xd9\xfd>\xc2\x17f\xbe\x91\'\x89=\x8d]"\xbd\xc6mt\xbe\x13f\x9a\xbd\xb57\xb8\xbe9\xd6\x15?U\xde\x8e=\x07B2=&S\x15?\x17H\x90=\xb2.\x8e\xbe{\x14\xae>{\xbd{=V+\x13\xbdG\x8f\x9f=

In [61]:
def tf_serialize_example(data):
  tf_string = tf.py_function(
    serialize_example,
    [data],  # pass these args to the above function.
    tf.string)      # the return type is `tf.string`.
  return tf.reshape(tf_string, ()) # The result is a scalar

In [62]:
dataset = tf.data.Dataset.from_tensor_slices(train_target)
serialized_dataset = dataset.map(tf_serialize_example)

In [63]:
serialized_dataset

<MapDataset shapes: (), types: tf.string>

In [64]:
filename = 'test.tfrecord'
writer = tf.data.experimental.TFRecordWriter(filename)
writer.write(serialized_dataset)

In [ ]:
with open(data[0].numpy(), 'r') as f:
  points_and_normals = f.readlines()

num_points = len(points_and_normals)
points = np.zeros((num_points, 3))
for idx, pnn in enumerate(points_and_normals):
  points[idx] = np.array(pnn.split(',')[0:3])


In [ ]:
points.shape

In [ ]:
_path = Path(modelnet_path)

In [ ]:
for p in _path.glob('*'):
  print(p)